#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.." || exit 1

GAMES=${GAMES:-3}
ALPHA_BIG2_DIR=${ALPHA_BIG2_DIR:-/Users/shukaihu/Code_Project_Local/AlphaBig2-codex}

ALPHA_BIG2_CKPT=${ALPHA_BIG2_CKPT:-${ALPHA_BIG2_DIR}/ML_AB/models/big2_transformer_best.pt} \
ALPHA_BIG2_AGENT=${ALPHA_BIG2_AGENT:-mcts} \
ALPHA_BIG2_MCTS_SECONDS=${ALPHA_BIG2_MCTS_SECONDS:-1.0} \
ALPHA_BIG2_MCTS_SELECTION=${ALPHA_BIG2_MCTS_SELECTION:-visits} \
ALPHA_BIG2_MCTS_POSTERIOR_PARTICLES=${ALPHA_BIG2_MCTS_POSTERIOR_PARTICLES:-24} \
ALPHA_BIG2_MCTS_HISTORY_WEIGHT=${ALPHA_BIG2_MCTS_HISTORY_WEIGHT:-1.0} \
ALPHA_BIG2_MCTS_ROOT_WARMUP=${ALPHA_BIG2_MCTS_ROOT_WARMUP:-12} \
ALPHA_BIG2_MCTS_ACTION_VALUE_FALLBACK_WEIGHT=${ALPHA_BIG2_MCTS_ACTION_VALUE_FALLBACK_WEIGHT:-0.0} \
BIG2_AGENT_COMMAND=${BIG2_AGENT_COMMAND:-/Users/shukaihu/Code_Project_Local/Big2VisionAgent-codex/alpha_big2_wrapper.py} \
uv run big2-agent autoplay-agent --executor packet --games "$GAMES"
